TRUNCATE TABLE role CASCADE;
TRUNCATE  TABLE reputation CASCADE;
TRUNCATE  TABLE votes_on_questions CASCADE;
TRUNCATE  TABLE question CASCADE;
TRUNCATE TABLE  votes_on_answers CASCADE;
TRUNCATE TABLE answer CASCADE;