TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE user_entity CASCADE;
TRUNCATE TABLE chat CASCADE;
TRUNCATE TABLE group_chat CASCADE;
TRUNCATE TABLE groupchat_has_users CASCADE;
TRUNCATE TABLE group_chat_moderator CASCADE;